language: c
compiler: gcc
before_install:
  - sudo add-apt-repository -y ppa:elementary-os/stable
  - sudo apt-get update -qq
  - sudo apt-get install -qq valac gobject-introspection libsqlheavy-dev libgtk-3-dev libgranite-dev libgee-dev cmake
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
branches:
  only:
    - develop
    - master
