language: c
compiler: gcc
before_install:
  - sudo add-apt-repository -y ppa:elementary-os/daily
  - sudo apt-get update  -y
  - sudo apt-get install -y valac gobject-introspection libsqlheavy-dev libgtk-3-dev libgranite-dev libgee-dev
env:
  - DEBIAN_FRONTEND=noninteractive
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd tests && ./envelope-tests
branches:
  only:
    - develop
    - master
