language: c
compiler: gcc
before_install:
  - sudo add-apt-repository -y ppa:elementary-os/stable
  - sudo apt-get update -qq -y
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew"  dist-upgrade -qq -y --force-yes
  - sudo apt-get install -y -qq valac gobject-introspection libsqlheavy-dev libgtk-3-dev libgranite-dev libgee-dev cmake
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
branches:
  only:
    - develop
    - master
