language: c
compiler: gcc
before_install:
  - sudo add-apt-repository -y ppa:vala-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq vala gobject-introspection libsqlheavy-dev libgtk-3-dev libgranite-dev cmake
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
branches:
  only:
    - develop
    - master
